// AUTO-GENERATED by pipeline/scripts/10-compile-app-data.mjs
// Do not edit manually. Re-run the script to update.
// Generated: 2026-03-03T00:12:59.389Z
// Total coasters: 3135

import rawCoasterData from './coasterIndex.json';

export interface CoasterIndexEntry {
  id: string;
  name: string;
  park: string;
  parkId: string;
  country: string;
  continent: string;
  manufacturer: string;
  material: string;
  type: string;
  heightFt: number;
  speedMph: number;
  lengthFt: number;
  inversions: number;
  yearOpened: number;
  dropFt?: number;
  gForce?: number;
  duration?: number;
  propulsion?: string;
  designer?: string;
  model?: string;
  status?: string;
  imageUrl?: string;
  popularityScore: number;
  popularityRank: number;
}

export const COASTER_INDEX: CoasterIndexEntry[] = rawCoasterData as CoasterIndexEntry[];

// Lookup map keyed by coaster ID
export const COASTER_BY_ID: Record<string, CoasterIndexEntry> = {};
for (const c of COASTER_INDEX) {
  COASTER_BY_ID[c.id] = c;
}
