// AUTO-GENERATED by pipeline/scripts/10-compile-app-data.mjs
// Do not edit manually. Re-run the script to update.
// Generated: 2026-03-03T00:12:59.393Z
// Total parks: 1240

import rawParkData from './parkIndex.json';

export interface ParkIndexEntry {
  id: string;
  name: string;
  country: string;
  region: string;
  city: string;
  coasterCount: number;
  status?: string;
  imageUrl?: string;
  owner?: string;
  wikiUrl?: string;
}

export const PARK_INDEX: ParkIndexEntry[] = rawParkData as ParkIndexEntry[];

// Lookup map keyed by park ID
export const PARK_BY_ID: Record<string, ParkIndexEntry> = {};
for (const p of PARK_INDEX) {
  PARK_BY_ID[p.id] = p;
}
