// AUTO-GENERATED by pipeline/scripts/10-compile-app-data.mjs
// Do not edit manually. Re-run the script to update.
// Generated: 2026-03-03T00:12:59.395Z

export interface TrendingCoasterEntry {
  rank: number;
  id: string;
  name: string;
  park: string;
  score: number;
  imageUrl?: string;
}

export interface PopularRideEntry {
  id: string;
  name: string;
  park: string;
  imageUrl?: string;
}

export interface PopularParkEntry {
  id: string;
  name: string;
  city: string;
  country: string;
  coasterCount: number;
  imageUrl?: string;
}

export const TRENDING_COASTERS: TrendingCoasterEntry[] = [
  {
    "rank": 1,
    "id": "kingda-ka",
    "name": "Kingda Ka",
    "park": "Six Flags Great Adventure",
    "score": 91.8,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Kingda_Ka.jpg"
  },
  {
    "rank": 2,
    "id": "top-thrill-2",
    "name": "Top Thrill 2",
    "park": "Cedar Point",
    "score": 89.6,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/TopThrill2.jpg"
  },
  {
    "rank": 3,
    "id": "superman-escape-from-krypton",
    "name": "Superman: Escape from Krypton",
    "park": "Six Flags Magic Mountain",
    "score": 84.9,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Superman_Escape_from_Krypton_tower.jpg"
  },
  {
    "rank": 4,
    "id": "millennium-force",
    "name": "Millennium Force",
    "park": "Cedar Point",
    "score": 84.8,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Millennium_Force_(Cedar_Point)_06.JPG"
  },
  {
    "rank": 5,
    "id": "steel-vengeance",
    "name": "Steel Vengeance",
    "park": "Cedar Point",
    "score": 82.1,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Steel_Vengeance_Drop_View.jpg"
  },
  {
    "rank": 6,
    "id": "x2",
    "name": "X2",
    "park": "Six Flags Magic Mountain",
    "score": 81.7,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/X2-firstdrop.jpg"
  },
  {
    "rank": 7,
    "id": "son-of-beast",
    "name": "Son of Beast",
    "park": "Kings Island",
    "score": 81.5,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/File%3APKI-Son_of_Beast.jpg"
  },
  {
    "rank": 8,
    "id": "pantherian",
    "name": "Pantherian",
    "park": "Kings Dominion",
    "score": 81.1,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Pantherian_at_Kings_Dominion_(wide_shot).jpg"
  },
  {
    "rank": 9,
    "id": "the-beast",
    "name": "The Beast",
    "park": "Kings Island",
    "score": 80.2,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/PKI-Beast.jpg"
  },
  {
    "rank": 10,
    "id": "sirens-curse",
    "name": "Siren's Curse",
    "park": "Cedar Point",
    "score": 79.4,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Siren%E2%80%99s_Curse_Cedar_Point_2025.jpg"
  }
];

export const POPULAR_RIDES: PopularRideEntry[] = [
  {
    "id": "top-thrill-2",
    "name": "Top Thrill 2",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/TopThrill2.jpg"
  },
  {
    "id": "millennium-force",
    "name": "Millennium Force",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Millennium_Force_(Cedar_Point)_06.JPG"
  },
  {
    "id": "steel-vengeance",
    "name": "Steel Vengeance",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Steel_Vengeance_Drop_View.jpg"
  },
  {
    "id": "x2",
    "name": "X2",
    "park": "Six Flags Magic Mountain",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/X2-firstdrop.jpg"
  },
  {
    "id": "pantherian",
    "name": "Pantherian",
    "park": "Kings Dominion",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Pantherian_at_Kings_Dominion_(wide_shot).jpg"
  },
  {
    "id": "the-beast",
    "name": "The Beast",
    "park": "Kings Island",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/PKI-Beast.jpg"
  },
  {
    "id": "sirens-curse",
    "name": "Siren's Curse",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Siren%E2%80%99s_Curse_Cedar_Point_2025.jpg"
  },
  {
    "id": "twisted-colossus",
    "name": "Twisted Colossus",
    "park": "Six Flags Magic Mountain",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/SFMM-_Twisted_Colossus.jpg"
  },
  {
    "id": "magnum-xl-200",
    "name": "Magnum XL-200",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Cedar_Shores_and_Magnum_XL-200_(2).png"
  },
  {
    "id": "leviathan",
    "name": "Leviathan",
    "park": "Canada's Wonderland",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Leviathan_Lift_and_Sculpture.jpg"
  },
  {
    "id": "goliath",
    "name": "Goliath",
    "park": "Six Flags Magic Mountain",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Goliath_at_Six_Flags_Magic_Mountain_(first_drop).jpg"
  },
  {
    "id": "el-toro",
    "name": "El Toro",
    "park": "Six Flags Great Adventure",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/KingdaEltoro.JPG"
  },
  {
    "id": "valravn",
    "name": "Valravn",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Cedar_Point_Valravn_track_(5232).jpg"
  },
  {
    "id": "formula-rossa",
    "name": "Formula Rossa",
    "park": "Ferrari World Abu Dhabi",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Formula_Rossa_coaster.jpg"
  },
  {
    "id": "steel-curtain",
    "name": "Steel Curtain",
    "park": "Kennywood",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/File%3AKennywood_-_48555800592.jpg"
  },
  {
    "id": "gatekeeper",
    "name": "GateKeeper",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/GateKeeper_004_(9547691513).jpg"
  },
  {
    "id": "jurassic-world-velocicoaster",
    "name": "Jurassic World VelociCoaster",
    "park": "Universal Orlando Resort",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Islands_of_Adventure_Orlando_(51149417278)_(cropped).jpg"
  },
  {
    "id": "maverick",
    "name": "Maverick",
    "park": "Cedar Point",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Maverick_Cedar_Point.jpg"
  },
  {
    "id": "steel-dragon-2000",
    "name": "Steel Dragon 2000",
    "park": "Nagashima Spa Land",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Steel_dragon_2000.jpg"
  },
  {
    "id": "the-smiler",
    "name": "The Smiler",
    "park": "Alton Towers Resort",
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/TheSmiler2015(2).JPG"
  }
];

export const POPULAR_PARKS: PopularParkEntry[] = [
  {
    "id": "unknown-park",
    "name": "Unknown Park",
    "city": "",
    "country": "Spain",
    "coasterCount": 32
  },
  {
    "id": "happy-valley",
    "name": "Happy Valley",
    "city": "",
    "country": "China",
    "coasterCount": 22
  },
  {
    "id": "cedar-point",
    "name": "Cedar Point",
    "city": "Sandusky, Ohio, U.S.",
    "country": "United States",
    "coasterCount": 18
  },
  {
    "id": "six-flags-magic-mountain",
    "name": "Six Flags Magic Mountain",
    "city": "26101 Magic Mountain Parkway\nValencia, California 91355",
    "country": "United States",
    "coasterCount": 16,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Six_Flags_Magic_Mountain_(13208988393).jpg"
  },
  {
    "id": "hersheypark",
    "name": "Hersheypark",
    "city": "Hershey, Pennsylvania, U.S.",
    "country": "United States",
    "coasterCount": 14,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Hersheypark_Entrance_10-2-2022.jpg"
  },
  {
    "id": "canadas-wonderland",
    "name": "Canada's Wonderland",
    "city": "Vaughan",
    "country": "United States",
    "coasterCount": 12
  },
  {
    "id": "carowinds",
    "name": "Carowinds",
    "city": "Charlotte, North Carolina and Fort Mill, South Carolina",
    "country": "United States",
    "coasterCount": 11,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Carowinds_aerial_view%2C_September_2017.JPG"
  },
  {
    "id": "busch-gardens-williamsburg",
    "name": "Busch Gardens Williamsburg",
    "city": "James City County",
    "country": "United States",
    "coasterCount": 10
  },
  {
    "id": "kings-dominion",
    "name": "Kings Dominion",
    "city": "Doswell",
    "country": "United States",
    "coasterCount": 10,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Kings_Dominion_logo.svg"
  },
  {
    "id": "kings-island",
    "name": "Kings Island",
    "city": "Mason, Ohio, U.S.",
    "country": "United States",
    "coasterCount": 10,
    "imageUrl": "https://en.wikipedia.org/wiki/Special:FilePath/Kings_Island_International_Street.jpg"
  }
];
